### ISSUE TITLE
profile picture

### ISSUE THREAD

**Issue by chpix** [jxing0831/Photo-Gallery#1]
![profile](https://user-images.githubusercontent.com/100942238/193440792-b4c874fc-15a3-49f4-b792-8b6cc0cce65e.png)

**Comment by chpix** [comment]
![头像](https://user-images.githubusercontent.com/100942238/193440913-cd30eb2b-1ff9-464f-a54b-1355a65627ad.jpg)

**Comment by jxing0831** [comment]
![profile](https://user-images.githubusercontent.com/100942238/193440925-df3f6800-2c71-45d1-b93c-79a275944427.jpg)

**Comment by jxing0831** [comment]
![profile](https://user-images.githubusercontent.com/100942238/193440928-b5dd3a9f-375a-4632-8170-baa2019c952b.png)
