### ISSUE TITLE
fly_SIAT

### ISSUE THREAD

**Issue by chpix** [jxing0831/Photo-Gallery#4]
![e3ddfb2fed0eb533d69c2fd2014bf96](https://user-images.githubusercontent.com/100942238/194549038-b1a620de-4b4b-41d0-87d7-fe27b145c838.jpg)

**Comment by jxing0831** [comment]
![image](https://user-images.githubusercontent.com/100942238/194714404-83fbc752-704d-45ef-b35a-aa4ca073b772.png)

**Comment by chpix** [comment]
![G@)1O8`MN(K~WR1B((HEN$V](https://user-images.githubusercontent.com/100942238/194714437-73fb51f1-9eba-4329-ad9d-29aefd6e3e25.jpg)

**Comment by chpix** [comment]
![N~VLL)I95}O~OYP~P92SE{5](https://user-images.githubusercontent.com/100942238/194853809-9770f832-38ab-4f11-b08b-df512be4cd06.png)
![CZUYU8DJ}1B{Z_0PI8%JDTP](https://user-images.githubusercontent.com/100942238/194853821-19aeb161-3fca-492f-b39d-1d958f519c14.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/195871144-e3bc5efd-5b30-49ee-ad73-b841d39446a2.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/195872292-8447f30b-fce1-408c-842e-2d8397d710e1.png)
![image](https://user-images.githubusercontent.com/100942238/195872320-aad8f0a2-a880-4dc3-9c5b-12ccf0924356.png)
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/195872569-5059ddb4-d138-4d27-acb4-a65cef2d564a.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/195872598-bf0b83de-58b4-472a-97ef-943c9d69464e.png)

**Comment by chpix** [comment]
![11](https://user-images.githubusercontent.com/100942238/196017890-144f2bb9-d294-4a11-9c6b-8078cf350f0b.jpg)
![22](https://user-images.githubusercontent.com/100942238/196017896-7dcdc83e-bdab-479d-9e7a-f0af2de9ff02.jpg)
![33](https://user-images.githubusercontent.com/100942238/196017901-727d7c20-c193-4941-b470-8e4a76903b1a.jpg)
![44](https://user-images.githubusercontent.com/100942238/196017903-1a90413f-4f75-4075-a49b-63610de710fc.jpg)
![c prime plus](https://user-images.githubusercontent.com/100942238/196017907-b8de1b32-f574-4560-90f2-ae680c8a157a.jpg)
![算法竞赛入门经典](https://user-images.githubusercontent.com/100942238/196017911-929e8b1d-c25b-40c7-8900-b6960bbcb274.jpg)
![挑战程序竞赛](https://user-images.githubusercontent.com/100942238/196017913-f12fd5b8-d35a-4d27-924a-07335ec31587.jpg)
![学习路线](https://user-images.githubusercontent.com/100942238/196017924-5e0cf7b2-9aaa-4ec1-9e50-8f8bed42c55b.jpg)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/196158999-60fb2d4a-46e7-4e44-9e60-2dd6409c1815.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/196998614-67700157-d1ff-490b-a83d-4fc861284348.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/203840883-81ef17c1-b9a5-4602-b530-a40af218a5ac.png)
