### ISSUE TITLE
GRI

### ISSUE THREAD

**Issue by chpix** [jxing0831/Photo-Gallery#7]
![2F8628116C469C9B2CF7D2A0C3B90C76](https://user-images.githubusercontent.com/100942238/206865016-f25b8490-c571-485e-8b18-35b5577cd52a.jpg)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/206865759-3e289b2c-b468-4878-ae5c-81db799ee3ad.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/206866552-174b11b0-ade3-4236-8111-0254829ac90d.png)

**Comment by jxing0831** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzlytKBSn36sIkCmo_E4V_x6XT-aC7uUj5WjkPd6wZ7fpYDQeh

**Comment by jxing0831** [comment]
![image](https://user-images.githubusercontent.com/100942238/206866961-a59d2342-e615-4953-9329-b1198664bf20.png)

**Comment by chpix** [comment]
![image](https://user-images.githubusercontent.com/100942238/206866976-50b21361-f07c-47b1-8bc9-625f1b0cb25a.png)
